steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/doublee-my-sql-tutorial:${SHORT_SHA}", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/doublee-my-sql-tutorial"]
    # deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "doublee-my-sql-tutorial",
        "--image",
        "gcr.io/$PROJECT_ID/doublee-my-sql-tutorial:${SHORT_SHA}",
        "--add-cloudsql-instances",
        "doublee-mysql",
        --set-env-vars,
        "INSTANCE_CONNECTION_NAME=doublee-sample-20210405:europe-west2:doublee-mysql",
        --set-env-vars,
        "DB_HOST=35.246.117.5",
        --set-env-vars,
        "DB_USER=admin",
        --set-env-vars,
        "DB_PASS=ktSQL1978",
        --set-env-vars,
        "DB_NAME=mysql_sample",
        "--region",
        "europe-west2",
        "--allow-unauthenticated",
        "--platform",
        "managed",
      ]
    env:
      - "PORT=8080"
images:
  - gcr.io/$PROJECT_ID/doublee-my-sql-tutorial
